mileage <- read.csv("C:/Users/krish/Downloads/mtcars.csv")
pairs(mileage[sapply(mileage, is.numeric)])
pairs(mileage)
cor(mileage)
model.car <- lm(mpg ~ hp + cyl + vs + wt, data = mileage)
summary(model.car)
reg_vol <- lm(mpg ~ cyl, data = mileage)
summary(reg_vol)
reg_wt <- lm(mpg ~ wt, data = mileage)
summary(reg_wt)
reg_wt_vol <- lm(mpg ~ wt + cyl, data = mileage)
summary(reg_wt_vol)
model.car <- lm(mpg ~ ., data = mileage)
summary(model.car)
install.packages("car", dependencies = TRUE)
library(car)
car::vif(model.car)
install.packages("MASS", dependencies = TRUE)
library(MASS)
stepAIC(model.car)
pairs(mileage)
cor(mileage)
model.car <- lm(mpg ~ ., data = mileage)
install.packages("car", dependencies = TRUE)
library(car)
car::vif(model.car)
plot(model.car)
residualPlots(model.car)
avPlots(model.car)
qqPlot(model.car)
influenceIndexPlot(model.car)
mileage["HP2"] <- mileage$hp * mileage$hp
mileage["SP2"] <- mileage$vs * mileage$vs
mileage1 <- mileage[-77, ]
model1 <- lm(mpg ~ ., data = mileage1)
summary(model1)
plot(model1)
residualPlots(model1)
qqPlot(model1)
influenceIndexPlot(model1)
mileage2 <- mileage[-c(77, 66, 81, 79), ]
model2 <- lm(mpg ~ ., data = mileage2[, -c(5, 4)])
summary(model2)
influenceIndexPlot(model2)
cor(mileage)
